timeout: 5
default_entry: 1
wallpaper: boot():/boot/limine/wallpaper.png
wallpaper_style: stretched
term_margin: 15
term_font_scale: 2x2
interface_resolution: 1024x768

/MagicalOS
    protocol: limine
    kernel_path: boot():/boot/kernel

    module_path: boot():/boot/initramfs.tar
    module_string: ramfs
